### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by LYRgood** [csiro-robotics/WildScenes#7]
What should I do to resolve this kind of error?

07/27 08:52:47 - mmengine - INFO - paramwise_options -- decode_head.fusion_conv.bn.bias:lr_mult=10.0
Traceback (most recent call last):
  File "/data1/dym/LYR/WildScenes-main/scripts/benchmark/train2d.py", line 111, in <module>
    main()
  File "/data1/dym/LYR/WildScenes-main/scripts/benchmark/train2d.py", line 107, in main
    runner.train()
  File "/data1/dym/anaconda3/envs/9517_proj/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1742, in train
    self._val_loop = self.build_val_loop(
  File "/data1/dym/anaconda3/envs/9517_proj/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1562, in build_val_loop
    loop = LOOPS.build(
  File "/data1/dym/anaconda3/envs/9517_proj/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/data1/dym/anaconda3/envs/9517_proj/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/data1/dym/anaconda3/envs/9517_proj/lib/python3.9/site-packages/mmengine/runner/loops.py", line 343, in __init__
    super().__init__(runner, dataloader)
  File "/data1/dym/anaconda3/envs/9517_proj/lib/python3.9/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/data1/dym/anaconda3/envs/9517_proj/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1370, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/data1/dym/anaconda3/envs/9517_proj/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/data1/dym/anaconda3/envs/9517_proj/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/data1/dym/LYR/WildScenes-main/wildscenes/mmseg_wildscenes/dataset/wildscenes.py", line 93, in __init__
    self.full_init()
  File "/data1/dym/anaconda3/envs/9517_proj/lib/python3.9/site-packages/mmengine/dataset/base_dataset.py", line 307, in full_init
    self.data_bytes, self.data_address = self._serialize_data()
  File "/data1/dym/anaconda3/envs/9517_proj/lib/python3.9/site-packages/mmengine/dataset/base_dataset.py", line 768, in _serialize_data
    data_bytes = np.concatenate(data_list)
ValueError: need at least one array to concatenate

**Comment by StephenHausler** [comment]
Hmm, I've not seen this error before. First, a couple things to check. Suggest placing a breakpoint in mmengine and checking what data is in data_list. Maybe there is no raw data present?
Suggest double checking that you have all raw 2D data files saved ok on your end, also you should check if the symlinks were created correctly by setup_data.py (e.g. make sure the symlinks are active and not broken).

**Comment by peymmo** [comment]
Closing this issue since there were no activities for a while. Please reopen if the issue is not resolved yet.
